# **Numpy part2:-**

In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,100,(2,2))
arr

array([[84, 65],
       [83, 14]])

In [3]:
arr.reshape(4,1)

array([[84],
       [65],
       [83],
       [14]])

## **flatten:-**

In [4]:
arr.flatten()

array([84, 65, 83, 14])

## **expend dimention:-**

In [5]:
arr=np.array([1,2,3,4])

In [6]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [7]:
arr.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [8]:
np.roll(arr,3)

array([2, 3, 4, 1])

# **Binary operation:-**

In [9]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [10]:
arr1+arr2

array([[ 9,  5,  6],
       [ 6, 10,  5],
       [15, 15,  6]])

In [11]:
arr1*arr2

array([[ 8,  6,  5],
       [ 9,  9,  4],
       [56, 56,  9]])

In [12]:
arr1%arr2

array([[1, 2, 0],
       [0, 0, 1],
       [1, 7, 0]])

In [13]:
arr1/arr2

array([[0.125     , 0.66666667, 5.        ],
       [1.        , 9.        , 0.25      ],
       [1.14285714, 0.875     , 1.        ]])

In [14]:
arr1-arr2

array([[-7, -1,  4],
       [ 0,  8, -3],
       [ 1, -1,  0]])

In [15]:
arr1**arr2

array([[      1,       8,       5],
       [     27,       9,       1],
       [2097152, 5764801,      27]])

In [16]:
arr1 & arr2

array([[0, 2, 1],
       [3, 1, 0],
       [0, 0, 3]])

In [17]:
~arr1

array([[ -2,  -3,  -6],
       [ -4, -10,  -2],
       [ -9,  -8,  -4]])

In [18]:
arr1>arr2

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

## **string function:-**

In [19]:
ar=np.array(["Abhishek","Upadhyay"])

In [20]:
ar

array(['Abhishek', 'Upadhyay'], dtype='<U8')

In [21]:
np.char.upper(ar)

array(['ABHISHEK', 'UPADHYAY'], dtype='<U8')

In [22]:
np.char.title(ar)

array(['Abhishek', 'Upadhyay'], dtype='<U8')

In [23]:
np.char.strip(ar)

array(['Abhishek', 'Upadhyay'], dtype='<U8')

## **Mathmatical function:-**

In [24]:
arr1

array([[1, 2, 5],
       [3, 9, 1],
       [8, 7, 3]])

In [25]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743, -0.95892427],
       [ 0.14112001,  0.41211849,  0.84147098],
       [ 0.98935825,  0.6569866 ,  0.14112001]])

In [26]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -3.38051501],
       [-0.14254654, -0.45231566,  1.55740772],
       [-6.79971146,  0.87144798, -0.14254654]])

In [27]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 2.23606798],
       [1.73205081, 3.        , 1.        ],
       [2.82842712, 2.64575131, 1.73205081]])

In [28]:
np.power(arr1,2)

array([[ 1,  4, 25],
       [ 9, 81,  1],
       [64, 49,  9]], dtype=int32)

In [29]:
np.mean(arr1)

4.333333333333333

In [30]:
np.std(arr1)

2.8674417556808756