# **numpy part 3:-**

In [1]:
import numpy as np

# **sorting,searching,counting:-**

In [2]:
arr=np.array([1,2,3,2,3,4])

In [3]:
np.sort(arr)

array([1, 2, 2, 3, 3, 4])

In [4]:
np.searchsorted(arr,4)

5

In [5]:
arr=np.array([0,231,231,0,0,0,23])

In [6]:
np.count_nonzero(arr)

3

In [7]:
np.where(arr>5)

(array([1, 2, 6], dtype=int64),)

In [8]:
np.extract(arr>12,arr)

array([231, 231,  23])

In [9]:
arr.byteswap()

array([         0, -419430400, -419430400,          0,          0,
                0,  385875968])

# **Copies and Views:-**

In [10]:
arr

array([  0, 231, 231,   0,   0,   0,  23])

In [11]:
a=np.copy(arr)

In [12]:
b=arr.view()

# **matrix library:-**

In [13]:
import numpy.matlib as nm

In [14]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [15]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **🔴linear algebra:-**

In [17]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [18]:
np.dot(arr1,arr2)

array([[ 77, 118, 159],
       [ 72, 113, 139],
       [ 81, 124, 137]])

In [19]:
arr1@arr2

array([[ 77, 118, 159],
       [ 72, 113, 139],
       [ 81, 124, 137]])