# **Numpy 1**

# **array,asarray,asanyarray:-**

In [1]:
import numpy as np

In [2]:
l=[1,2,4,54]
arr=np.array(l)
type(arr)

numpy.ndarray

In [3]:
np.array([[1,2],[23,23]])

array([[ 1,  2],
       [23, 23]])

# **Matrix:-**

In [4]:
b=np.matrix(l)
b

matrix([[ 1,  2,  4, 54]])

In [5]:
l=[1,2,3,4]
a=np.array(l)

In [6]:
c=a
c[0]=100
c

array([100,   2,   3,   4])

In [7]:
d=np.copy(c)
d

array([100,   2,   3,   4])

# **From function:-**

In [8]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [9]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

# **from iter:-**

In [10]:
iterable=(i*i for i in range(5))

In [11]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

# **from string:-**

In [12]:
np.fromstring("234 1223",sep=" ")

array([ 234., 1223.])

# **Data types:-**

In [13]:
l=[2,3,4,5,6,7,8,9]
ar=np.array(l)
ar.ndim

1

In [14]:
l=([[2,3,4,5],[2,13,12,23]])
ar=np.array(l)
ar.ndim

2

# **shape:-**

In [15]:
ar.shape

(2, 4)

In [16]:
ar.dtype

dtype('int32')

# **arange:-**

arange(start point,end point,jumped)

In [17]:
np.arange(2.3,5.4,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

# **linespace:-**

In [18]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# **zeros:-**

In [19]:
np.zeros(((2,4,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# **ones:-**

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# **Empty:-**

In [21]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

# **identity matrix;-**

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **logspace:-**

In [23]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

# **🔴random:-**

### **randn:-**
randn function is used where mean is 0 and satnderd deviation is 1

In [24]:
arr1=np.random.randn(3,4)
import pandas as pd
pd.DataFrame(arr1)


0         1         2         3
0  0.196633  0.195401  0.659375 -0.421908
1 -0.678849  1.165026 -1.071528 -0.308900
2  0.297876  0.757108 -0.344147 -0.765323

# **rand:-**

In [25]:
arr1=np.random.rand(3,4)
import pandas as pd
pd.DataFrame(arr1)

0         1         2         3
0  0.841138  0.688185  0.018628  0.561041
1  0.965107  0.303834  0.154861  0.446820
2  0.444498  0.596311  0.083526  0.965646

# **randint:-**

In [26]:
arr1=np.random.randint(1,100,(10,2))
import pandas as pd
pd.DataFrame(arr1).to_csv("test.csv")

In [27]:
arr1

array([[15, 53],
       [68, 15],
       [20, 64],
       [59, 40],
       [95, 66],
       [83, 63],
       [57, 64],
       [60, 98],
       [87, 92],
       [72, 83]])

# **indexing:-**

In [28]:
arr1[1][1]

15

In [29]:
arr1[2:5,1]

array([64, 40, 66])

In [30]:
arr1=np.random.randint(1,100,(3,3))
arr1

array([[24, 71, 60],
       [10, 71, 12],
       [90, 66,  9]])

In [31]:
arr1>50

array([[False,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

## **Arithmatic operation;-**

In [32]:
arr1=np.random.randint(1,20,(3,3))
arr2=np.random.randint(1,20,(3,3))
arr1+arr2

array([[24, 32, 24],
       [15, 21,  9],
       [18, 30,  8]])

## **@ for multiplication** 

In [33]:
arr1=np.random.randint(1,20,(3,3))
arr2=np.random.randint(1,20,(3,3))
arr1@arr2

array([[507, 225, 300],
       [613, 282, 423],
       [423, 214, 351]])

# **🔴Broadcasting:-**

In [34]:
arr1=np.zeros((4,4))

In [35]:
row=np.array([1,2,3,4])

In [36]:
arr1+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

# **transpose:-**

In [37]:
row.T

array([1, 2, 3, 4])

In [38]:
ar=np.random.randint(1,100,(3,4))
np.log10(ar)

array([[0.77815125, 0.60205999, 1.60205999, 1.92941893],
       [0.90308999, 1.67209786, 1.81954394, 1.14612804],
       [1.23044892, 1.97772361, 1.98677173, 1.86923172]])